export const sidebar = {
    '/blog/about/':[
        {
            text:'了解我',
            items:[
                {text:'自我介绍',link:'/blog/about/'}
            ]
        }
    ],
    '/blog/docs/':[
        {
            text:'建设中',
            items:[
                {text:'第一篇文章',link:'/blog/docs/Introduction'}
            ]
        }
    ],
    '/blog/MC/':[
        {
            text:'Minecraft',
            items:[
                {text:'简介',link:'/blog/MC/Introduction'}
            ]
        }
    ],
    '/blog/AE2/':[
        {
            text:'Applied Energistics 2',
            items:[
                {text:'简介',link:'/blog/AE2/Introduction'},
                {
                    text:'基础教程',
                    items:[
                        {text:'频道',link:'/blog/AE2/guide/Channel'},
                    ]
                }
            ],
        },
    ]
}