name: Algolia DocSearch Crawler

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Prepare DocSearch Configuration
        id: prepare_config
        run: |
          RAW_CONFIG_JSON=$(jq -c . < algolia.config.json)
          SAFELY_QUOTED_CONFIG_JSON=$(printf %q "$RAW_CONFIG_JSON")
          echo "config_output=$SAFELY_QUOTED_CONFIG_JSON" >> "$GITHUB_OUTPUT"

      - name: Run Algolia DocSearch Crawler
        run: |
          docker run --rm \
            -e "APPLICATION_ID=${{ secrets.DOCSEARCH_APPLICATION_ID }}" \
            -e "API_KEY=${{ secrets.DOCSEARCH_ADMIN_API_KEY }}" \
            -e "CONFIG=${{ steps.prepare_config.outputs.config_output }}" \
            algolia/docsearch-scraper
