name: Algolia DocSearch Crawler

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Algolia DocSearch Crawler
        run: |
          docker run --rm \
            -e "APPLICATION_ID=${{ secrets.DOCSEARCH_APPLICATION_ID }}" \
            -e "API_KEY=${{ secrets.DOCSEARCH_ADMIN_API_KEY }}" \
            -e "CONFIG=$(cat <<EOF
            {
              "index_name": "SakuraBlog",
              "start_urls": ["https://www.sakuraonline.cn/"],
              "rateLimit": 8,
              "maxDepth": 10,
              "js_render": true,
              "sitemaps": ["https://www.sakuraonline.cn/sitemap.xml"],
              "exclusion_patterns": [],
              "ignore_canonical_to": false,
              "discovery_patterns": ["https://www.sakuraonline.cn/**"],
              "schedule": "at 05:10 on Saturday",
              "selectors": {
                "lvl0": {
                  "selector": ".VPNavBarTitle > span",
                  "default_value": "Documentation"
                },
                "lvl1": ".content h1",
                "lvl2": ".content h2",
                "lvl3": ".content h3",
                "lvl4": ".content h4",
                "lvl5": ".content h5",
                "text": ".content p, .content li"
              },
              "selectors_exclude": [
                "aside", ".page-footer", ".next-and-prev-link", ".table-of-contents"
              ],
              "custom_settings": {
                "attributesForFaceting": ["type", "lang"],
                "attributesToRetrieve": ["hierarchy", "content", "anchor", "url"],
                "attributesToHighlight": ["hierarchy", "hierarchy_camel", "content"],
                "attributesToSnippet": ["content:10"],
                "camelCaseAttributes": ["hierarchy", "hierarchy_radio", "content"],
                "searchableAttributes": [
                  "unordered(hierarchy_radio_camel.lvl0)", "unordered(hierarchy_radio.lvl0)",
                  "unordered(hierarchy_radio_camel.lvl1)", "unordered(hierarchy_radio.lvl1)",
                  "unordered(hierarchy_radio_camel.lvl2)", "unordered(hierarchy_radio.lvl2)",
                  "unordered(hierarchy_radio_camel.lvl3)", "unordered(hierarchy_radio.lvl3)",
                  "unordered(hierarchy_radio_camel.lvl4)", "unordered(hierarchy_radio.lvl4)",
                  "unordered(hierarchy_radio_camel.lvl5)", "unordered(hierarchy_radio.lvl5)",
                  "unordered(hierarchy_radio_camel.lvl6)", "unordered(hierarchy_radio.lvl6)",
                  "unordered(hierarchy_camel.lvl0)", "unordered(hierarchy.lvl0)",
                  "unordered(hierarchy_camel.lvl1)", "unordered(hierarchy.lvl1)",
                  "unordered(hierarchy_camel.lvl2)", "unordered(hierarchy.lvl2)",
                  "unordered(hierarchy_camel.lvl3)", "unordered(hierarchy.lvl3)",
                  "unordered(hierarchy_camel.lvl4)", "unordered(hierarchy.lvl4)",
                  "unordered(hierarchy_camel.lvl5)", "unordered(hierarchy.lvl5)",
                  "unordered(hierarchy_camel.lvl6)", "unordered(hierarchy.lvl6)",
                  "content"
                ],
                "distinct": true,
                "attributeForDistinct": "url",
                "customRanking": [
                  "desc(weight.pageRank)",
                  "desc(weight.level)",
                  "asc(weight.position)"
                ],
                "ranking": [
                  "words", "filters", "typo", "attribute", "proximity", "exact", "custom"
                ],
                "highlightPreTag": "<span class=\"algolia-docsearch-suggestion--highlight\">",
                "highlightPostTag": "</span>",
                "minWordSizefor1Typo": 3,
                "minWordSizefor2Typos": 7,
                "allowTyposOnNumericTokens": false,
                "minProximity": 1,
                "ignorePlurals": true,
                "advancedSyntax": true,
                "attributeCriteriaComputedByMinProximity": true,
                "removeWordsIfNoResults": "allOptional"
              }
            }
          EOF
            )" \
            algolia/docsearch-scraper
