name: Algolia Crawler

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run Algolia DocSearch Crawler
        run: |
          export CONFIG=$(jq -c . < algolia.config.json)
          docker run \
            -e APPLICATION_ID="${{ secrets.DOCSEARCH_APPLICATION_ID }}" \
            -e API_KEY="${{ secrets.DOCSEARCH_API_KEY }}" \
            -e CONFIG="$CONFIG" \
            algolia/docsearch-scraper
